### ISSUE TITLE
数学公式无法渲染的解决方法

### ISSUE THREAD

**Issue by qybit** [elkan1788/hugo-theme-next#1]
参考了这篇博客：[在Hugo中使用MathJax](https://note.qidong.name/2018/03/hugo-mathjax/)

**Comment by elkan1788** [comment]
@qybit  感谢提供帮助，如果方便的话，可以提交一下你的request代码，可以把它合并进来。

**Comment by elkan1788** [comment]
使用mathjax方式解决，只需要在文章的开头添加`math: true`参数即可。
