### ISSUE TITLE
css 加载失败

### ISSUE THREAD

**Issue by huarong8** [elkan1788/hugo-theme-next#11]
按照教程部署后，页面css失效

**Comment by elkan1788** [comment]
麻烦详细说明下操作步骤，另外建议在本地调试时使用谷歌浏览器测试。

**Comment by appdev** [comment]
+1 操作步骤基本跟快速开始一样

clone 到本地
拷贝 config和content 到根目录
hugo 生成

**Comment by appdev** [comment]
config里面的地址也改了

**Comment by elkan1788** [comment]
@appdev @huarong8 能否打开浏览器在，在Console面板上看下网络状态显示什么错误。另外`config`中的`BaseURL`参数不影响CSS内容加载的。

**Comment by RyanTokManMokMTM** [comment]
本地可以加載 但是部署後css 無法加載  因為路徑不一樣了
本地是 localhost:131/css/main.css
例如部署Github page: github.io/myweb/
css 位置會是github.io/css/ 而不是github.io/myweb/css

**Comment by elkan1788** [comment]
> 本地可以加載 但是部署後css 無法加載 因為路徑不一樣了 本地是 localhost:131/css/main.css 例如部署Github page: github.io/myweb/ css 位置會是github.io/css/ 而不是github.io/myweb/css

@RyanTokManMokMTM 了解问题的原因，这个是引用相对引用路径的问题，后续我调整一下试试，不过一般github page的博客都是你的githubid作为主域名，类似这样的形式：githubid.github.io，建议你也可以试下在你的github仓库上创建个 githubid.githui.io 的仓库即可。
