### ISSUE TITLE
此主题不能用呀!

### ISSUE THREAD

**Issue by zoushucai** [elkan1788/hugo-theme-next#12]
我按照教程来的可是不运行,一直不出结果,(mac电脑上)

**Comment by elkan1788** [comment]
@zoushucai 请详细说明下你的操作流程，不然无法进行定位分析，谢谢。

**Comment by zoushucai** [comment]
@elkan1788   谢谢, 您能抽空看看吗?  我按照您的步骤来,可是运行不出来,总爱卡在这里
![image](https://user-images.githubusercontent.com/15843338/142805548-71502a13-31be-4bea-bc90-11e15497e8b5.png)



这里我录了一个小视频. 谢谢(我也改过配置,  看了一些资料, 说要其他配置之类的, 比如hugo-extended, 我下载了也不行,这我就不懂了,我个人理解,模板应该只需要hugo就好了)

链接: https://pan.baidu.com/s/1N1yrsyrbALKig84b2FJjKA 提取码: clu2

**Comment by zoushucai** [comment]
> @elkan1788 谢谢, 您能抽空看看吗? 我按照您的步骤来,可是运行不出来,总爱卡在这里 ![image](https://user-images.githubusercontent.com/15843338/142805548-71502a13-31be-4bea-bc90-11e15497e8b5.png)
> 
> 这里我录了一个小视频. 谢谢(我也改过配置, 看了一些资料, 说要其他配置之类的, 比如hugo-extended, 我下载了也不行,这我就不懂了,我个人理解,模板应该只需要hugo就好了).
> 
> 链接: https://pan.baidu.com/s/1N1yrsyrbALKig84b2FJjKA 提取码: clu2

**Comment by elkan1788** [comment]
不好意思，看样子你已经解决这个问题，这个情况主要是官方提供的模板中有Twitter和Yutobe的shortcode引用，如果没有外网访问权限确实是会卡住几分钟的，后续我会更新下示例模板就可解决。
