### ISSUE TITLE
404页面啥都没有

### ISSUE THREAD

**Issue by haiyux** [elkan1788/hugo-theme-next#13]

**Comment by elkan1788** [comment]
看样子是腾讯那边的公益404引用脚本有问题，具体情况还在分析中。

**Comment by haiyux** [comment]
博客 不考虑使用github issue 评论吗   用这个utteranc.es

**Comment by elkan1788** [comment]
@haiyux 暂不考虑，因为utteranc.es要注册github才能使用，对于评论者来说约束太多不自由。
