### ISSUE TITLE
2022年份似乎不能正确显示

### ISSUE THREAD

**Issue by Reisen1969** [elkan1788/hugo-theme-next#15]
markdown 里 这样写

![image](https://user-images.githubusercontent.com/76834109/147842939-abce512f-1676-4b5f-9e76-88a283d863ce.png)

网页里是这样的:

![image](https://user-images.githubusercontent.com/76834109/147842950-2a1de4b8-bfb6-4e6b-8b23-c5f18bdc4605.png)

但是2021年的就是正常的

**Comment by haiyux** [comment]
你的date格式错误了 应该这样像 `2022-01-02T17:03:34+08:00`

**Comment by Reisen1969** [comment]
> 

感谢回复
