### ISSUE TITLE
为什么我的启动Hugo服务之后全是报错？

### ISSUE THREAD

**Issue by sanbeichahegongheguo** [elkan1788/hugo-theme-next#2]
C:\Users\time\Documents\MEGA\个人文章\myblog>hugo server

Start building sites …
ERROR 2021/03/06 03:26:32 render of "page" failed: execute of template failed: template: _default/single.html:14:9: executing "main_content" at <partial "post/date.html" .>: error calling partial: "C:\Users\time\Documents\MEGA\个人文章\myblog\themes\hugo-theme-next\layouts\partials\post\date.html:4:96": execute of template failed: template: partials/post/date.html:4:96: executing "partials/post/date.html" at <.Site.Params.DateFormat>: invalid value; expected string
ERROR 2021/03/06 03:26:32 render of "page" failed: execute of template failed: template: _default/single.html:14:9: executing "main_content" at <partial "post/date.html" .>: error calling partial: "C:\Users\time\Documents\MEGA\个人文章\myblog\themes\hugo-theme-next\layouts\partials\post\date.html:4:96": execute of template failed: template: partials/post/date.html:4:96: executing "partials/post/date.html" at <.Site.Params.DateFormat>: invalid value; expected string
ERROR 2021/03/06 03:26:32 render of "page" failed: execute of template failed: template: _default/single.html:14:9: executing "main_content" at <partial "post/date.html" .>: error calling partial: "C:\Users\time\Documents\MEGA\个人文章\myblog\themes\hugo-theme-next\layouts\partials\post\date.html:4:96": execute of template failed: template: partials/post/date.html:4:96: executing "partials/post/date.html" at <.Site.Params.DateFormat>: invalid value; expected string
ERROR 2021/03/06 03:26:32 render of "page" failed: execute of template failed: template: _default/single.html:14:9: executing "main_content" at <partial "post/date.html" .>: error calling partial: "C:\Users\time\Documents\MEGA\个人文章\myblog\themes\hugo-theme-next\layouts\partials\post\date.html:4:96": execute of template failed: template: partials/post/date.html:4:96: executing "partials/post/date.html" at <.Site.Params.DateFormat>: invalid value; expected string
Built in 64 ms
Error: Error building site: failed to render pages: render of "page" failed: execute of template failed: template: _default/single.html:14:9: executing "main_content" at <partial "post/date.html" .>: error calling partial: "C:\Users\time\Documents\MEGA\个人文章\myblog\themes\hugo-theme-next\layouts\partials\post\date.html:4:96": execute of template failed: template: partials/post/date.html:4:96: executing "partials/post/date.html" at <.Site.Params.DateFormat>: invalid value; expected string

**Comment by sanbeichahegongheguo** [comment]
hugo v0.81.0-59D15C97

**Comment by elkan1788** [comment]
@sanbeichahegongheguo  你好，请问你的部署方式是什么样的呢？我本地的hugo 版本是v0.80.0-792EF0F4，所以对你那个版本是兼容的，你可以参考一下exampleSite目录下的目录结构。 

建议你可以先尝试下把主题克隆下来好，进入到exmapleSite目录下，执行如下的命令：
`hugo server -t ../..`
看下是否可以正常运行，正常的输出如下：
![image](https://user-images.githubusercontent.com/1217096/110235807-06f7d480-7f6d-11eb-822b-7e08c3878e3c.png)
> 注意：如是当前网络不可以访问外网，建议删除`rich-content.md`文件里面的内容。

**Comment by sanbeichahegongheguo** [comment]
> 
> 
> @sanbeichahegongheguo 你好，请问你的部署方式是什么样的呢？我本地的hugo 版本是v0.80.0-792EF0F4，所以对你那个版本是兼容的，你可以参考一下exampleSite目录下的目录结构。
> 
> 建议你可以先尝试下把主题克隆下来好，进入到exmapleSite目录下，执行如下的命令：
> `hugo server -t ../..`
> 看下是否可以正常运行，正常的输出如下：
> ![image](https://user-images.githubusercontent.com/1217096/110235807-06f7d480-7f6d-11eb-822b-7e08c3878e3c.png)
> 
> > 注意：如是当前网络不可以访问外网，建议删除`rich-content.md`文件里面的内容。

感谢回复呢。我试了好几个`themes`，都有类似的问题。

现在换了一个新的模板，就没这个问题了。目前就只能先用着它那个吧。咱们这个是我最喜欢的，可惜先用不上了。

**Comment by elkan1788** [comment]
好的，后续如有回归使用，欢迎吐嘈，哈
