### ISSUE TITLE
"toc: true"不能生成文章目录

### ISSUE THREAD

**Issue by jin-li** [elkan1788/hugo-theme-next#21]
我记得在hexo的next主题中，在文章开头中加入"toc: true"的话，当浏览文章时左侧的sidebar会自动显示目录，如下图所示：
![Screenshot_select-area_20220219184537](https://user-images.githubusercontent.com/26253144/154822879-5a5fd8fe-b2fd-4b8f-a837-94b20d11b9ca.png)

但是我在用这个主题时，再文章开头中加入"toc: true"之后，浏览文章时并没有显示目录，如下图所示：
![Screenshot_select-area_20220219184918](https://user-images.githubusercontent.com/26253144/154822966-42920060-6068-4707-8d03-5abc3c86b753.png)

是还需要做一些其他设置吗？

**Comment by elkan1788** [comment]
是的，文章目录是根据文章中的`标题`来自动生成的，另外要注意要不使用标题1格式，从标题2开始启用。
![image](https://user-images.githubusercontent.com/1217096/159123473-0c4d92f4-340e-450c-ab21-bf8e2af72f21.png)

**Comment by Reisen1969** [comment]
我想问一下为什么 要从标题2 启用呢,  能否让标题1  也生效吗

**Comment by elkan1788** [comment]
> 在hexo的next主题中，在文章开头中加入"toc: true"的话，当浏览文章时左侧的sidebar会自动显示目录，如下

这个似乎是`Hugo`的默认限制，暂时没有找到方案。
