### ISSUE TITLE
请问分类这个选项要怎么设置?

### ISSUE THREAD

**Issue by Reisen1969** [elkan1788/hugo-theme-next#25]
![image](https://user-images.githubusercontent.com/76834109/163699536-c2cdcff7-337c-4cba-8aae-d9362f8f10b8.png)

**Comment by elkan1788** [comment]
这个是根据文本来自动生成的，你可以在文章头部加上：categories 说明分类名称，参考如下 ：

```
---
title: 优化Hugo Next主题的过程2
url: "2021/07/09/make-next-theme-pithy2.html"
date: "2021-07-09T17:53:06+08:00"
draft: false
tags:
  - NexT
  - 博客
  - Hugo
  // 下面这个就是分类名称
categories: 
  - 博客
toc: true
---
```

有其他使用问题，可以到讨论区 [Discussions](https://github.com/elkan1788/hugo-theme-next/discussions) 发帖！
