### ISSUE TITLE
样式有问题

### ISSUE THREAD

**Issue by haiyux** [elkan1788/hugo-theme-next#27]
<img width="1086" alt="image" src="https://user-images.githubusercontent.com/57396775/167236083-aa236a09-842e-4923-a213-108bf83cdabf.png">

**Comment by elkan1788** [comment]
@haiyux  使用的是哪个浏览器，麻烦提供下名称，版本和屏幕分辨率，谢谢。

**Comment by elkan1788** [comment]
近期有对样式文件做过调整，也有可能是缓存的原图，建议先清除下本地缓存试试看。

**Comment by haiyux** [comment]
分辨率  3072 × 1920  chrome safira 都是这样 缓存清了

**Comment by elkan1788** [comment]
> 分辨率 3072 × 1920 chrome safira 都是这样 缓存清了

收到，原来又是高分屏幕，难怪测试不出来。

**Comment by elkan1788** [comment]
问题已经修复！

**Comment by haiyux** [comment]
![27A1312A-F7C5-421A-A60F-88C09DB8E47C](https://user-images.githubusercontent.com/57396775/167242608-c006d2ad-3978-4504-bb41-e891483d8720.png)

**Comment by haiyux** [comment]
![image](https://user-images.githubusercontent.com/57396775/167242622-331b4aa7-4113-4558-8265-6a3a1688c7f9.png)

再往下翻翻就碟在一起了 还是有有问题
