### ISSUE TITLE
请问文章内代码块支持行号吗？

### ISSUE THREAD

**Issue by duny31030** [elkan1788/hugo-theme-next#29]
我没有在配置中找到行号的相关信息
请问目前是否支持文章内的代码块开启行号？

**Comment by elkan1788** [comment]
不好意思，暂时不支持，欢迎扩展一下或者关注后续的迭代（近期会有较大的版本发布，全面同步官方的最新版本）

**Comment by elkan1788** [comment]
@duny31030  新版本的 NexT 主题已经实现你想要的效果： [Hugo 内置的 Chroma 语法高亮](https://hugo-next-dev.vercel.app/syntax-highlighting.html)， 可关注后续的发布。
