### ISSUE TITLE
PC端27寸显示器下看博客只集中在左半部分

### ISSUE THREAD

**Issue by PeiLeiScott** [elkan1788/hugo-theme-next#3]
![image](https://user-images.githubusercontent.com/61865468/120108345-5bd76f80-c197-11eb-91ed-56a0daa05ca6.png)

**Comment by tanmx** [comment]
the same

**Comment by elkan1788** [comment]
能否提供下你的操作系统和浏览器的版本？这里应该是浏览器兼容性所导致的。

**Comment by JefferyWang** [comment]
> 能否提供下你的操作系统和浏览器的版本？这里应该是浏览器兼容性所导致的。

系统版本：Mac OS11.2.3,
Chrome版本：87.0.4280.141
Safari版本： 14.0.3 (16610.4.3.1.7)
试了都是一样的效果，27寸显示器，显示偏左

**Comment by MLZC** [comment]
同样的问题

系统版本：macOS Big Sur 11.6
Safari版本：Version 15.0 (16612.1.29.41.4, 16612)

**Comment by elkan1788** [comment]
@MLZC @JefferyWang  问题已经定位是CSS中设置了个1600像素的限制，现在可以访问[我的空间站](https://lisenhui.cn)体验下。
